### ISSUE TITLE
Prepare the Solr Operator for an Apache Release

### ISSUE THREAD

**Issue by HoustonPutman** [apache/solr-operator#235]
There are a few items that need to be completed for the Solr Operator to be able to have it's first release

- [x] Migrate the repo to apache/solr-operator #234 
- [x] Create the Docker repo apache/solr-operator [INFRA-21545](https://issues.apache.org/jira/browse/INFRA-21545)
- [ ] Create the Solr Operator sub-page of the Solr website (https://solr.apache.org/operator)
- [x] Make the Solr Operator an official sub-project of Apache Solr [SOLR-15211](https://issues.apache.org/jira/browse/SOLR-15211)
- [x] Complete all necessary licensing steps for a source and binary docker release #228 
- [x] Create a release wizard for the Solr Operator #243
- [ ] Find a way to host the Solr Operator documentation on the Solr Operator website. (Optional)

**Comment by HoustonPutman** [comment]
All pieces are in place. The Solr Operator sub-page of solr.apache.org will be merged after the release is complete, as it requires the first apache release to exist.

**Comment by drano** [comment]
Have you an idea about availability of 0.3.0 version ?

**Comment by HoustonPutman** [comment]
> Have you an idea about availability of 0.3.0 version ?

There is currently an ongoing release candidate. We will likely need a second candidate. But i would expect a full v0.3.0 release in the next two weeks.

see here on how to try out the release candidate:
https://lists.apache.org/thread.html/rda8ce14cded2f655966d60c9274fe0111985557beda7da1e0854a8dd%40%3Cdev.solr.apache.org%3E
